apiVersion: v1
kind: Secret
metadata:
  name: htpasswd
  namespace: openshift-config
type: Opaque
data:
  htpasswd: YmxlZGk6JGFwcjEkaDc0R0xXTVAkVzMuSGV5T0xqRUlzU3pHekJ5QU1LLwo=
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd